export const para1 =
   'The terms and conditions stated herein (collectively, the “Agreement”) constitute a legal agreement between you and Yachtime app. In order to use the Service (defined below) and the associated Application (defined below) you must agree to the terms and conditions that are set out below. By using or receiving any services supplied to you by Yachtime app (collectively, the “Service”), and downloading, installing or using any associated application or web service supplied by the Yachtime app which purpose is to enable you to use the Service (collectively, the “Application”), you hereby expressly acknowledge and agree to be bound by the terms and conditions of the Agreement, and any future amendments and additions to this Agreement as published from time to time in the Application in the Terms of Service section.';

export const para2 =
   'THESE TERMS INCLUDE A BINDING ARBITRATION CLAUSE AND A CLASS ACTION WAIVER. IF YOU LIVE IN THE US, THESE TERMS AFFECT YOUR RIGHTS TO RESOLVE A DISPUTE WITH YACHTIME APP AND YOU SHOULD REVIEW THESE TERMS CAREFULLY.';

export const para3 =
   'Yachtime app reserves the right to modify the terms and conditions of this Agreement or its policies relating to the Service or Application at any time, effective upon posting of an updated version of this Agreement on the Service or Application. You are responsible for regularly reviewing this Agreement. Continued use of the Service or Application after any such changes shall constitute your consent to such changes.';

export const para4 =
   'You will be responsible for arranging charters with a Yacht Charter Owner, through the Yachtime app Application, Yachtime app’s website(s) or other method acceptable to Yachtime app. Acceptable methods may include email, text message or telephone with a Yacht Charter Owner.';

export const para5 =
   'You agree to open an account with Yachtime app and to provide all requested information, including a credit card to be kept on file to be used for payment/capture for services according to these terms and conditions, as well as others which may be included on new updates of Yachtime app website and mobile application. When subscribed to a membership, a payment will be processed for the Total Price stated on the App and/or Website as follows:';

export const para6 =
   'If a subscription to a membership plan is confirmed then Yachtime app will charge you a non-refundable subscription payment, that will be charged again at the end of the time corresponding to the purchased subscription.';
export const para7 =
   'Yachtime app, at its sole discretion, may make promotional offers with different features and different rates to any of our customers. These promotional offers, unless made to you, shall have no bearing whatsoever on your offer or contract. Yachtime app may change the fees for our Service or Application, as we deem necessary for our business. We encourage you to check back at our website periodically if you are interested about how we charge for the Service of Application.';
export const para8 =
   'Payment for Services shall be subject to the following terms and conditions, which may be amended from time to time, at the discretion of Yachtime app.';

export const para9 =
   'DISCLAIMER OF RESPONSIBILITY FOR THE AGREEMENTS AND RELATIONSHIPS CREATED THROUGH CHAT ON THE YACHTIMEAPP PLATFORM , OTHER';
export const para10 =
   "The Yachtime application will not be responsible for any actions or relationships created between users through the platform's chat. Yachtime App is hereby released from any claim or demand for any direct or consequential damages arising from the breach as a result of a force majeure event, whether or not listed herein or other event mentioned above.";
export const para11 =
   'INSURANCE. It is the sole responsibility of the owner of the yacht to maintain liability insurance coverage, including proper charter insurance. Yachtime app is not liable for any claims arising in connection with or related to the yacht.';

export const para12 =
   'By using the Application or Service, you expressly represent and warrant that you are legally entitled to enter into this Agreement. If you reside in a jurisdiction that restricts the use of the Service because of age, or restricts the ability to enter into agreements such as this one due to age, you must abide by such age limits and you must not use the Application and Service. Without limiting the foregoing, the Service and Application is not available to children (persons under the age of 18). By using the Application or Service, you represent and warrant that you are at least 18 years old. By using the Application or the Service, you represent and warrant that you have the right, authority and capacity to enter into this Agreement and to abide by the terms and conditions of this Agreement. Your participation in using the Service and/or Application is for your sole, personal use. You may not authorize others to use your user status, and you may not assign or otherwise transfer your user account to any other person or entity. When using the Application or Service you agree to comply with all applicable laws from your home nation, the country, state and city in which you are present while using the Application or Service.';

export const para13 =
   'You may only access the Service using authorized means. It is your responsibility to check to ensure you download the correct Application for your device. Yachtime app is not liable if you do not have a compatible handset or if you have downloaded the wrong version of the Application for your handset. Yachtime app reserves the right to terminate this Agreement should you be using the Service or Application with an incompatible or unauthorized device.';

export const para14 =
   'Subject to your compliance with the terms and conditions of this Agreement, Yachtime app grants you a limited, non-exclusive, non-transferable license: (i) to view, download and print any Yachtime app Content solely for your personal and non-commercial purposes; and (ii) to view any User Content to which you are permitted access solely for your personal and non- commercial purposes. You have no right to sublicense the license rights granted in this section.';
export const para15 =
   'You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Service, Application or Collective Content, except as expressly permitted in this Agreement. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Yachtime app or its licensors, except for the licenses and rights expressly granted in this Agreement.';

export const para16 =
   'We may, in our sole discretion, permit Users to post, upload, publish, submit or transmit User Content. By making available any User Content on or through the Service or Application, you hereby grant to Yachtime app a worldwide, irrevocable, perpetual, non-exclusive, transferable, royalty-free license, with the right to sublicense, to use, view, copy, adapt, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast and otherwise exploit such User Content only on, through or by means of the Service or Application. Yachtime app does not claim any ownership rights in any User Content and nothing in this Agreement will be deemed to restrict any rights that you may have to use and exploit any User Content.';

export const para17 =
   'You acknowledge and agree that you are solely responsible for all User Content that you make available through the Service or Application. Accordingly, you represent and warrant that: (i) you either are the sole and exclusive owner of all User Content that you make available through the Service or Application or you have all rights, licenses, consents and releases that are necessary to grant to Yachtime app and to the rights in such User Content, as contemplated under this Agreement; and (ii) neither the User Content nor your posting, uploading, publication, submission or transmittal of the User Content or Yachtime app’s use of the User Content (or any portion thereof) on, through or by means of the Service or Application will infringe, misappropriate or violate a third party’s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.';

export const para18 =
   'Subject to your compliance with this Agreement, Yachtime app grants you a limited non-exclusive, non-transferable license to download and install a copy of the Application on a single mobile device or computer that you own or control and to run such copy of the Application solely for your own personal use. Furthermore, with respect to any Application accessed through or downloaded from the Apple App Store (“App Store Sourced Application”), you will use the App Store Sourced Application only: (i) on an Apple-branded product that runs iOS (Apple’s proprietary operating system software); and (ii) as permitted by the “Usage Rules” set forth in the Apple App Store Terms of Service. Yachtime app reserves all rights in and to the Application not expressly granted to you under this Agreement.';

export const para19 =
   'You acknowledge and agree that (i) this Agreement is concluded between you and Yachtime app only, and not Apple, and (ii) Yachtime app, not Apple, is solely responsible for the App Store Sourced Application and content thereof. Your use of the App Store Sourced Application must comply with the App Store Terms of Service. You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App Store Sourced Application. In the event of any failure of the App Store Sourced Application to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App Store Sourced Application to you and to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App Store Sourced Application. As between Yachtime app and Apple, any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of Yachtime app. You and Yachtime app acknowledge that, as between Yachtime app and Apple, Apple is not responsible for addressing any claims you have or any claims of any third party relating to the App Store Sourced Application or your possession and use of the App Store Sourced Application, including, but not limited to: (i) product liability claims; (ii) any claim that the App Store Sourced Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation. You and Yachtime app acknowledge that, in the event of any third party claim that the App Store Sourced Application or your possession and use of that App Store Sourced Application infringes that third party’s intellectual property rights, as between Yachtime app and Apple, Yachtime app, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by this Agreement. You and Yachtime app acknowledge and agree that Apple, and Apple’s subsidiaries, are third party beneficiaries of this Agreement as related to your license of the App Store Sourced Application, and that, upon your acceptance of the terms and conditions of this Agreement, Apple will have the right (and will be deemed to have accepted the right) to enforce this Agreement as related to your license of the App Store Sourced Application against you as a third party beneficiary thereof. Without limiting any other terms of this Agreement, you must comply with all applicable third party terms of agreement when using the App Store Sourced Application.';

export const para20 =
   'You shall not (i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Service or the Application in any way; (ii) modify or make derivative works based upon the Service or the Application; (iii) create Internet “links” to the Service or “frame” or “mirror” any Application on any other server or wireless or Internet-based device; (iv) reverse engineer or access the Application in order to (a) build a competitive product or service, (b) build a product using similar ideas, features, functions or graphics of the Service or Application, or (c) copy any ideas, features, functions or graphics of the Service or Application, or (v) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Service or Application.';

export const para21 =
   'You shall not: (i) send spam or otherwise duplicative or unsolicited messages in violation of applicable laws; (ii) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including material harmful to children or violative of third party privacy rights; (iii) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs; (iv) interfere with or disrupt the integrity or performance of the Application or Service or the data contained therein; or (v) attempt to gain unauthorized access to the Application or Service or its related systems or networks.';

export const para22 =
   'Yachtime app will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. Yachtime app may involve and cooperate with law enforcement authorities in prosecuting users who violate this Agreement. You acknowledge that Yachtime app has no obligation to monitor your access to or use of the Service, Application or Collective Content or to review or edit any Collective Content, but has the right to do so for the purpose of operating the Service and Application, to ensure your compliance with this Agreement, or to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body. Yachtime app reserves the right, at any time and without prior notice, to remove or disable access to any Collective Content that Yachtime app, at its sole discretion, considers to be in violation of this Agreement or otherwise harmful to the Service or Application.';

export const para23 =
   'Yachtime app respects copyright law and expects its users to do the same. It is Yachtime app’s policy to terminate in appropriate circumstances Users or other account holders who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders.';

export const para24 =
   'Yachtime app alone (and its licensors, where applicable) shall own all right, title and interest, including all related intellectual property rights, in and to the Application and the Service and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Application or the Service. This Agreement is not a sale and does not convey to you any rights of ownership in or related to the Application or the Service, or any intellectual property rights owned by Yachtime app. The Yachtime app name, Yachtime app logo, and the product names associated with the Application and Service are trademarks of Yachtime app or third parties, and no right or license is granted to use them.';

export const para25 =
   'During use of the Application and Service, you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of third party service providers, advertisers or sponsors showing their goods and/or services through the Application or Service. Any such activity, and any terms, conditions, warranties or representations associated with such activity, is solely between you and the applicable third- party. Yachtime app and its licensors shall have no liability, obligation or responsibility for any such correspondence, purchase, transaction or promotion between you and any such third- party. Yachtime app does not endorse any sites on the Internet that are linked through the Service or Application, and in no event shall Yachtime app or its licensors be responsible for any content, products, services or other materials on or available from such sites or third party providers. Yachtime app provides the Application and Service to you pursuant to the terms and conditions of this Agreement. You recognize, however, that certain third-party providers of goods and/or services may require your agreement to additional or different terms and conditions prior to your use of or access to such goods or services, and Yachtime app disclaims any and all responsibility or liability arising from such agreements between you and the third party providers.';

export const para26 =
   'Yachtime app may rely on third party advertising and marketing supplied through the Application or Service and other mechanisms to subsidize the Application or Service. By agreeing to these terms and conditions you agree to receive such advertising and marketing. If you do not want to receive such advertising you should notify us in writing. Yachtime app reserves the right to charge you a higher fee for the Service or Application should you choose not to receive these advertising services. You can ask for the amount os this higher fee, if applicable, sending an email to yachtime.app@gmail.com. Yachtime app may compile and release information regarding you and your use of the Application or Service on an anonymous basis as part of a customer profile or similar report or analysis. You agree that it is your responsibility to take reasonable precautions in all actions and interactions with any third party you interact with through the Service.';

export const para27 =
   'By entering into this Agreement and using the Application or Service, you agree that you shall defend, indemnify and hold Yachtime app, its licensors and each such party’s parent organizations, subsidiaries, affiliates, officers, directors, Users, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys’ fees and costs) arising out of or in connection with: (a) your violation or breach of any term of this Agreement or any applicable law or regulation, whether or not referenced herein; (b) your violation of any rights of any third party, including providers of transportation services arranged via the Service or Application, or (c) your use or misuse of the Application or Service.';

export const para28 =
   'THE COMPANY MAKES NO REPRESENTATION, WARRANTY, OR GUARANTY AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, AVAILABILITY, ACCURACY OR COMPLETENESS OF THE SERVICE OR APPLICATION. THE COMPANY DOES NOT REPRESENT OR WARRANT THAT (A) THE USE OF THE SERVICE OR APPLICATION WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE OR OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, APPLICATION, SYSTEM OR DATA, (B) THE SERVICE OR APPLICATION WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (C) ANY STORED DATA WILL BE ACCURATE OR RELIABLE, (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (E) ERRORS OR DEFECTS IN THE SERVICE OR APPLICATION WILL BE CORRECTED, OR (F) THE SERVICE OR THE SERVER(S) THAT MAKE THE SERVICE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THE SERVICE AND APPLICATION IS PROVIDED TO YOU STRICTLY ON AN “AS IS” BASIS. ALL CONDITIONS, REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS, ARE HEREBY DISCLAIMED TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW BY THE COMPANY. THE COMPANY MAKES NO REPRESENTATION, WARRANTY, OR GUARANTY AS TO THE RELIABILITY, SAFETY, TIMELINESS, QUALITY, SUITABILITY OR AVAILABILITY OF ANY SERVICES, PRODUCTS OR GOODS OBTAINED BY THIRD PARTIES THROUGH THE USE OF THE SERVICE OR APPLICATION. YOU ACKNOWLEDGE AND AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR USE OF THE APPLICATION AND SERVICE, AND ANY THIRD PARTY SERVICES OR PRODUCTS REMAINS SOLELY WITH YOU, TO THE MAXIMUM EXTENT PERMITTED BY LAW.';

export const para29 =
   "THE COMPANY'S SERVICE AND APPLICATION MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. THE COMPANY IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS.";

export const para30 =
   'IN NO EVENT SHALL THE COMPANY’S AGGREGATE LIABILITY EXCEED THE AMOUNTS ACTUALLY PAID BY AND/OR DUE FROM YOU IN THE SIX (6) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH CLAIM. IN NO EVENT SHALL THE COMPANY AND/OR ITS LICENSORS BE LIABLE TO ANYONE FOR ANY INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES OF ANY TYPE OR KIND (INCLUDING PERSONAL INJURY, LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE). THE COMPANY AND/OR ITS LICENSORS SHALL NOT BE LIABLE FOR ANY LOSS, DAMAGE OR INJURY WHICH MAY BE INCURRED BY YOU, INCLUDING BY NOT LIMITED TO LOSS, DAMAGE OR INJURY ARISING OUT OF, OR IN ANY WAY CONNECTED WITH THE SERVICE OR APPLICATION, INCLUDING BUT NOT LIMITED TO THE USE OR INABILITY TO USE THE SERVICE OR APPLICATION, ANY RELIANCE PLACED BY YOU ON THE COMPLETENESS, ACCURACY OR EXISTENCE OF ANY ADVERTISING, OR AS A RESULT OF ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY THIRD PARTY SERVICE PROVIDER, ADVERTISER OR SPONSOR WHOSE ADVERTISING APPEARS ON THE WEBSITE OR IS REFERRED BY THE SERVICE OR APPLICATION, EVEN IF THE COMPANY AND/OR ITS LICENSORS HAVE BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.';

export const para31 =
   'THE COMPANY MAY INTRODUCE YOU TO THIRD PARTY LICENSED YACHT CHARTER PROVIDERS FOR THE PURPOSES OF PROVIDING YACHT CHARTER SERVICES. WE WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY THIRD PARTY YACHT CHARTER PROVIDERS AND YOU EXPRESSLY WAIVE AND RELEASE THE COMPANY FROM ANY AND ALL LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO THE THIRD PARTY TRAVEL PROVIDER. THE COMPANY WILL NOT BE A PARTY TO DISPUTES, NEGOTIATIONS OF DISPUTES BETWEEN YOU AND SUCH THIRD PARTY PROVIDERS. WE CANNOT AND WILL NOT PLAY ANY ROLE IN MANAGING PAYMENTS BETWEEN YOU AND THE THIRD PARTY PROVIDERS. RESPONSIBILITY FOR THE DECISIONS YOU MAKE REGARDING SERVICES OFFERED VIA THE APPLICATION OR SERVICE (WITH ALL ITS IMPLICATIONS) RESTS SOLELY WITH YOU. WE WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY SUCH THIRD PARTIES AND YOU EXPRESSLY WAIVE AND RELEASE THE COMPANY FROM ANY AND ALL LIABILITY, CLAIMS, CAUSES OF ACTION, OR DAMAGES ARISING FROM YOUR USE OF THE APPLICATION OR SERVICE, OR IN ANY WAY RELATED TO THE THIRD PARTIES INTRODUCED TO YOU BY THE APPLICATION OR SERVICE. YOU EXPRESSLY WAIVE AND RELEASE ANY AND ALL RIGHTS AND BENEFITS UNDER SECTION 1542 OF THE CIVIL CODE OF THE STATE OF CALIFORNIA (OR ANY ANALOGOUS LAW OF ANY OTHER STATE), WHICH READS AS FOLLOWS: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM, MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.”';

export const para32 =
   'THE QUALITY OF THE CHARTER SERVICES SCHEDULED THROUGH THE USE OF THE SERVICE OR APPLICATION IS ENTIRELY THE RESPONSIBILITY OF THE THIRD PARTY PROVIDER WHO ULTIMATELY PROVIDES SUCH TRANSPORTATION SERVICES TO YOU. YOU UNDERSTAND, THEREFORE, THAT BY USING THE APPLICATION AND THE SERVICE, YOU MAY BE EXPOSED TO CHARTER SERVICES THAT ARE POTENTIALLY DANGEROUS, OFFENSIVE, HARMFUL TO MINORS, UNSAFE OR OTHERWISE OBJECTIONABLE, AND THAT YOU USE THE APPLICATION AND THE SERVICE AT YOUR OWN RISK.';

export const para33 =
   'Yachtime app may give notice by means of a general notice on the Service, electronic mail to your email address on record in the Yachtime app’s account information, or by written communication sent by first class mail or pre-paid post to your address on record in the Yachtime app’s account information. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email). You may give notice to Yachtime app (such notice shall be deemed given when received by Yachtime app) at any time by any of the following:  letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail to Yachtime app at the following addresses (whichever is appropriate): Yachtime app. 7751 nw 107 ave unit 817 doral Fl 33178, United States.';

export const para34 =
   'This Agreement may not be assigned by you without the prior written approval of Yachtime app but may be assigned without your consent by Yachtime app to (i) a parent or subsidiary, (ii) an acquirer of assets, or (iii) a successor by merger. Any purported assignment in violation of this section shall be void.';

export const para35 =
   'You agree to comply fully with all U.S. and foreign export laws and regulations to ensure that neither the Application nor any technical data related thereto nor any direct product thereof is exported or re-exported directly or indirectly in violation of, or used for any purposes prohibited by, such laws and regulations. By using the App Store Sourced Application, you represent and warrant that: (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.';

export const para36 =
   'You and Yachtime app agree that any dispute, claim or controversy arising out of or relating to this Agreement or the breach, termination, enforcement, interpretation or validity thereof or the use of the Service or Application (collectively, “Disputes”) will be settled by binding arbitration, except that each party retains the right to bring an individual action in small claims court and the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party’s copyrights, trademarks, trade secrets, patents or other intellectual property rights. You acknowledge and agree that you and Yachtime app are each waiving the right to a trial by jury or to participate as a plaintiff or class member in any purported class action or representative proceeding. Further, unless both you and Yachtime app otherwise agree in writing, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Dispute Resolution” section will be deemed void. Except as provided in the preceding sentence, this “Dispute Resolution” section will survive any termination of this Agreement.';

export const para37 =
   'Arbitration Rules and Governing Law.The arbitration will be administered by the American Arbitration Association (“AAA”) in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the “AAA Rules”) then in effect, except as modified by this “Dispute Resolution” section. (The AAA Rules are available at www.adr.org/arb_med or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this Section.';

export const para38 =
   'Arbitration Process.A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. (The AAA provides a form Demand for Arbitration at www.adr.org/aaa/ShowPDF?doc=ADRSTG_004175 and a separate form for California residents at www.adr.org/aaa/ShowPDF?doc=ADRSTG_015822 .) The arbitrator will be either a retired judge or an attorney licensed to practice law in the state of Florida or Delaware and will be selected by the parties from the AAA’s roster of consumer dispute arbitrators. If the parties are unable to agree upon an arbitrator within seven (7) days of delivery of the Demand for Arbitration, then the AAA will appoint the arbitrator in accordance with the AAA Rules.';

export const para39 =
   'Arbitration Location and Procedure.Unless you and Yachtime app otherwise agree, the arbitration will be conducted in the county where you reside. If your claim does not exceed $10,000, then the arbitration will be conducted solely on the basis of documents you and Yachtime app submit to the arbitrator, unless you request a hearing or the arbitrator determines that a hearing is necessary. If your claim exceeds $10,000, your right to a hearing will be determined by the AAA Rules. Subject to the AAA Rules, the arbitrator will have the discretion to direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration.';

export const para40 =
   'Arbitrator’s Decision.The arbitrator will render an award within the time frame specified in the AAA Rules. The arbitrator’s decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator’s award damages must be consistent with the terms of the “Limitation of Liability” section above as to the types and the amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant’s individual claim. If you prevail in arbitration you will be entitled to an award of attorneys’ fees and expenses, to the extent provided under applicable law. Yachtime app will not seek, and hereby waives all rights it may have under applicable law to recover, attorneys’ fees and expenses if it prevails in arbitration.';

export const para41 =
   'Fees.It is your responsibility to pay any AAA filing, administrative and arbitrator fees will be solely as set forth in the AAA Rules. However, if your claim for damages does not exceed $75,000, Yachtime app will pay all such fees unless the arbitrator finds that either the substance of your claim or the relief sought in your Demand for Arbitration was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)).';
export const para42 =
   'Changes.Notwithstanding the provisions of the modification-related provisions above, if Yachtime app changes this “Dispute Resolution” section after the date you first accepted this Agreement (or accepted any subsequent changes to this Agreement), you may reject any such change by sending us written notice (including by email to concierge@Yachtime app.club) within 30 days of the date such change became effective, as indicated in the “Last Updated Date” above or in the date of Yachtime app’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and Yachtime app in accordance with the provisions of this “Dispute Resolution” section as of the date you first accepted this Agreement (or accepted any subsequent changes to this Agreement).';
export const para43 =
   'No joint venture, partnership, employment, or agency relationship exists between you, Yachtime app or any third party provider as a result of this Agreement or use of the Service or Application. If any provision of the Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. The failure of Yachtime app to enforce any right or provision in this Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by Yachtime app in writing. This Agreement comprises the entire agreement between you and Yachtime app and supersedes all prior or contemporaneous negotiations, discussions or agreements, whether written or oral, between the parties regarding the subject matter contained herein.';
